logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:

    url: jdbc:mysql://banco-meetup-api.mysql.database.azure.com:3306/meetupdb?serverTimezone=UTC
    username: meetupdb@banco-meetup-api
    password: Azure1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true